return {
	["Name"] = "Sheep",
	["Family"] = "Animals",
	["__BrainProfile"] = "PassivePrey",
	["__Stats"] = {
		["Health"] = 22,
		["MaxHealth"] = 22,
		["PhysicalAttack"] = 0,
		["Speed"] = 6,
	},
	["__Animations"] = {
		["Walk"] = "rbxassetid://110151614180287",
		["Run"] = "rbxassetid://115993230462172",
	},
	["__Drops"] = {
		{
			ItemKind = "InventoryItem",
			ItemId = "Meat",
			Quantity = 1,
			Chance = 1,
		},
		{
			ItemKind = "InventoryItem",
			ItemId = "Wool",
			Quantity = 1,
			Chance = 0.2,
		},
	},
}
